# Generated by Django 3.1 on 2020-08-24 02:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1)),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Sign Date')),
                ('birth_day', models.DateTimeField(verbose_name='Birth Date')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='Address')),
                ('description', models.TextField(null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='avatars/%Y/%m/%d', verbose_name='Avatar')),
                ('compet_certificate', models.FileField(null=True, upload_to='certifications/%Y/%m/%d', verbose_name='Competition Certificates')),
                ('active', models.BooleanField(default=True, verbose_name='Active Player')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'db_table': 'player',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solved_Cubes',
            fields=[
                ('cube_id', models.AutoField(primary_key=True, serialize=False)),
                ('cube_name', models.CharField(max_length=150, verbose_name='Cube Name')),
                ('cube_image', models.ImageField(null=True, upload_to='', verbose_name='Cube Image')),
                ('cube_description', models.TextField(null=True, verbose_name='Description')),
                ('users', models.ManyToManyField(to='players.Player')),
            ],
            options={
                'verbose_name': 'Cube',
                'verbose_name_plural': 'Cubes',
                'db_table': 'solved_cube',
                'ordering': ['cube_name'],
            },
        ),
        migrations.CreateModel(
            name='PlayerReview',
            fields=[
                ('solved_cubes_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='players.solved_cubes')),
                ('player_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='players.player')),
                ('headline', models.CharField(max_length=200)),
                ('date_publication', models.DateField(default=datetime.datetime.now)),
                ('abstract', models.TextField(null=True)),
                ('url', models.TextField()),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'review',
                'ordering': ['headline'],
            },
            bases=('players.player', 'players.solved_cubes'),
        ),
        migrations.CreateModel(
            name='Telephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=3, verbose_name='Country Code ')),
                ('telephone', models.CharField(max_length=10, verbose_name='Telephone')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
            ],
            options={
                'verbose_name': 'Telehone',
                'verbose_name_plural': 'Telephones',
                'db_table': 'telephone',
                'ordering': ['user_id'],
            },
        ),
    ]
